baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "AbterPHP Documentation"
theme = "hugo-theme-learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/abtercms/abtercms.com/edit/master/abterphp/content/"
  description = "Documentation for AbterPHP"
  author = "Team AbterCMS"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "green"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Documentation for AbterCMS"
weight = 1
languageName = "English"

[Languages.hu]
title = "AbterPHP dokumentáció"
weight = 1
languageName = "Magyar"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/abtercms/abtercms.com/tree/master/abterphp"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-globe'></i> AbterCMS website"
identifier = "website"
url = "https://abtercms.com/"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-book'></i> AbterCMS documentation"
identifier = "abtercms"
url = "https://docs.abtercms.com/"
weight = 30

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 40

[[Languages.hu.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/abtercms/abtercms.com/tree/master/abterphp"
weight = 10

[[Languages.hu.menu.shortcuts]]
name = "<i class='fas fa-fw fa-globe'></i> AbterCMS weboldal"
identifier = "website"
url = "https://abtercms.com/"
weight = 20

[[Languages.hu.menu.shortcuts]]
name = "<i class='fas fa-fw fa-book'></i> AbterCMS dokumentáció"
identifier = "abtercms"
url = "https://docs.abtercms.com/"
weight = 30

[[Languages.hu.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Közreműködők"
url = "/credits"
weight = 40
